#!/bin/bash

create_vm() {
    vm_name=$1
    os=$2
    size=$3
    username=$4
### Pour info, je n'ai pas encore réussi à faire marcher ArchLinux, donc ça doit sûrement venir de l'image que j'utilise
    case $os in
        "Archlinux")
            os_variant="archlinux"
            cloud_init_config=$(cat <<EOF
#cloud-config
system_info:
  default_user:
    name: ${username}
    home: /home/${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
password: ${username}
chpasswd: { expire: False }
hostname: ${vm_name}
ssh_authorized_keys:
    - $(cat ~/.ssh/id_ed25519.pub)

ssh_pwauth: True
package_upgrade: true
packages:
- neofetch

runcmd:
- echo "feur" > feur.txt

EOF
)
            ;;
        "Debian")
            os_variant="debian"
            cloud_init_config=$(cat <<EOF
#cloud-config
system_info:
  default_user:
    name: ${username}
    home: /home/${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
password: ${username}
chpasswd: { expire: False }
hostname: ${vm_name}
ssh_authorized_keys:
    - $(cat ~/.ssh/id_ed25519.pub)

ssh_pwauth: True
package_upgrade: true
packages:
- neofetch

runcmd:
- echo "feur" > feur.txt

EOF
)
            ;;
        "Fedora")
            os_variant="fedora"
            cloud_init_config=$(cat <<EOF
#cloud-config
system_info:
  default_user:
    name: ${username}
    home: /home/${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
password: ${username}
chpasswd: { expire: False }
hostname: ${vm_name}
ssh_authorized_keys:
    - $(cat ~/.ssh/id_ed25519.pub)

ssh_pwauth: True
package_upgrade: true
packages:
- neofetch

runcmd:
- echo "feur" > feur.txt

EOF
)
            ;;
        "Ubuntu")
            os_variant="ubuntu"
            cloud_init_config=$(cat <<EOF
#cloud-config
system_info:
  default_user:
    name: ${username}
    home: /home/${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
password: ${username}
chpasswd: { expire: False }
hostname: ${vm_name}
ssh_authorized_keys:
    - $(cat ~/.ssh/id_ed25519.pub)

ssh_pwauth: True
package_upgrade: true
packages:
- neofetch

runcmd:
- echo "feur" > feur.txt

EOF
)
            ;;
        *)
            echo "Choix invalide."
            exit 1
            ;;
    esac

    case $size in
        "10G")
            disk_size="10"
            ;;
        "20G")
            disk_size="20"
            ;;
        "30G")
            disk_size="30"
            ;;
        "Personnaliser")
            read -p "Entrez la taille custom: " custom_size
            disk_size="$custom_size"
            ;;
        *)
            echo "Choix invalide."
            exit 1
            ;;
    esac

    virt-install --name "$vm_name" --vcpu 4 --memory 4096 --os-variant "detect=on" \
                 --disk size="${disk_size}",backing_store="/VM/VMImages/${os_variant}-base.qcow2" \
                 --cloud-init user-data=<(echo "$cloud_init_config") \
                 --graphics none --noautoconsole --import
}

create_ssh_config() {
    ip_address=$(virsh domifaddr "$1" | awk '/ipv4/ {split($4, a, "/"); print a[1]}')

    if grep -q "include ~/.ssh/vm_config" ~/.ssh/config; then 
        echo "La configuration SSH pour les VM est déjà présente dans ~/.ssh/config"; 
    else
        echo "include ~/.ssh/vm_config" >> ~/.ssh/config;
        echo "Ajout de la config SSH des VM dans ~/.ssh/config";
    fi

    cat <<EOF >> ~/.ssh/vm_config
Host ${vm_name}
    HostName ${ip_address}
    User ${username}
    IdentitiesOnly yes
    IdentityFile "~/.ssh/id_ed25519"
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com
EOF
}

read -p "Entrer le nom de la VM: " vm_name

echo "Choisir un OS:"
select os_choice in "Archlinux" "Debian" "Fedora" "Ubuntu"; do
    break
done

echo "Choisir la taille du stockage:"
select size_choice in "10G" "20G" "30G" "Personnaliser"; do
    break
done

read -p "Entrez votre nom d'utilisateur: " username

create_vm "$vm_name" "$os_choice" "$size_choice" "$username"

echo "Attendez 1 minute le temps que la VM se fasse et prends une adresse IP"
sleep 60

create_ssh_config 